### ISSUE TITLE
Zoom level is set to the middle of the route/polyline and does not display route in its entirety

### ISSUE THREAD

**Issue by sharon-ho** [felixlapierre/campus-guide#70]
**Description:**
- Currently the camera zoom level when the polyline is added is set to the center of the polyline, which does not work well for long routes

**Steps to reproduce:**
1. Click on the Navigate button
2. Select "Search for location"
3. Enter start and end location as to be several kilometers apart (ex. Enter start as "Université de Montréal" and enter end location as "Concordia University Sir George Williams")
5. Click "Go"

**Expected:**
- Entire route is visible on the map; the map camera should zoom out to display the route in its entirety

**Actual:**
- Only a small portion of the route is visible, because the view is zoomed in too far; the map camera is centered in the middle of the route and does not display the route in its entirety

**Workaround:**
- Manually zoom out on the map to view the full polyline in its entirety

**Screenshot:**
- What happens after imputing "Cafe Myriade" and "H3Y1S4" into the start and destination respectively:

![Screenshot_1583104316](https://user-images.githubusercontent.com/33813045/75635944-5f70f500-5be8-11ea-9dc2-2ec712b5adc1.png)

**Comment by felixlapierre** [comment]
Steps to reproduce:
- Click on the Navigate button
- Select "Search for location"
- Enter start as "Université de Montréal"
- Enter end location as "Concordia University Sir George Williams"
- Click go

Expected:
- Entire route is visible on the map

Actual:
- Only a small portion of the route is visible, because the view is zoomed in too far
